# Generated by Django 5.2.7 on 2025-10-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gauravgowebsite', '0004_remove_contact_isread_remove_contact_mdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='game_type',
            field=models.CharField(choices=[('ftp', 'Free to Play Games'), ('br', 'Battle Royale Games'), ('fps', 'FPS Games'), ('rpg', 'RPG Games'), ('sim', 'Simulation Games'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
