# Generated by Django 5.2.7 on 2025-10-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gauravgowebsite', '0005_games_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='additional_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
        migrations.AddField(
            model_name='games',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='game_files/'),
        ),
    ]
