# Generated by Django 4.1.5 on 2025-10-17 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gauravgowebsite', '0003_remove_contact_isread_remove_contact_mdate_and_more'),
        ('gauravgowebsite', '0005_games_game_type'),
    ]

    operations = [
    ]
