# Generated by Django 5.2.7 on 2025-10-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gauravgowebsite', '0006_games_additional_description_games_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='file_size',
            field=models.CharField(default='31mb', max_length=50),
        ),
        migrations.AddField(
            model_name='games',
            name='platforms',
            field=models.CharField(default='Web, Android, iOS', max_length=200),
        ),
        migrations.AddField(
            model_name='games',
            name='publisher',
            field=models.CharField(default='GauravGo Games', max_length=200),
        ),
        migrations.AddField(
            model_name='games',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='games',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
