# Generated by Django 5.2.7 on 2025-10-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gauravgowebsite', '0007_games_file_size_games_platforms_games_publisher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
