# Generated by Django 4.1.5 on 2025-10-26 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gauravgowebsite', '0006_merge_20251017_1827'),
        ('gauravgowebsite', '0008_games_youtube_link'),
    ]

    operations = [
    ]
