# Generated by Django 4.1.5 on 2025-10-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gauravgowebsite', '0009_merge_20251026_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='file_upload',
        ),
        migrations.AddField(
            model_name='games',
            name='play_store_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
